name: Build ApexLite Jar

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17 for Gradle
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Jar (Target Java 8)
      run: gradle jar --no-daemon -Dorg.gradle.java.home=$JAVA_HOME

    - name: Upload Jar Artifact
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: ApexLite-Client-Jar
        path: build/libs/*.jar
